import 'dart:math' as math;
import 'package:flutter/material.dart';
import '../../services/auth_service.dart';
import '../dashboard/dashboard_screen.dart';

class LoginScreen extends StatefulWidget { const LoginScreen({super.key}); @override State<LoginScreen> createState()=>_LoginScreenState(); }
class _LoginScreenState extends State<LoginScreen> with SingleTickerProviderStateMixin {
  final emailController=TextEditingController(); final passwordController=TextEditingController(); late final AnimationController _waterController; bool _loading=false;
  static const _logo='https://raw.githubusercontent.com/thegkexpert662-afk/arank-india/main/assets/images/logos/logo.png';
  @override void initState(){super.initState();_waterController=AnimationController(vsync:this,duration:const Duration(seconds:8))..repeat();}
  @override void dispose(){emailController.dispose();passwordController.dispose();_waterController.dispose();super.dispose();}
  Future<void> _login() async { if(emailController.text.trim().isEmpty||passwordController.text.isEmpty){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Please enter email and password.')));return;} setState(()=>_loading=true); final error=await AdminAuthService().signIn(email:emailController.text,password:passwordController.text); if(!mounted)return; if(error!=null){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(error)));setState(()=>_loading=false);return;} Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const DashboardScreen())); }
  @override Widget build(BuildContext context)=>Scaffold(body:Stack(fit:StackFit.expand,children:[AnimatedBuilder(animation:_waterController,builder:(_,__)=>CustomPaint(painter:_WaterPainter(_waterController.value))),Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:430),child:Card(elevation:18,color:Colors.white.withOpacity(.94),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(28)),child:Padding(padding:const EdgeInsets.fromLTRB(34,34,34,30),child:Column(mainAxisSize:MainAxisSize.min,children:[Container(width:112,height:112,padding:const EdgeInsets.all(12),decoration:BoxDecoration(shape:BoxShape.circle,color:Colors.white,boxShadow:[BoxShadow(color:Colors.blue.withOpacity(.16),blurRadius:24,spreadRadius:3)]),child:ClipOval(child:Image.network(_logo,fit:BoxFit.contain,errorBuilder:(_,__,___)=>const Icon(Icons.school_rounded,size:62,color:Color(0xff1769E0))))),const SizedBox(height:18),const Text('ARank India Admin',style:TextStyle(fontSize:28,fontWeight:FontWeight.w800,color:Color(0xff15233D))),const SizedBox(height:6),const Text('Admin Panel',style:TextStyle(fontSize:14,color:Color(0xff64748B),fontWeight:FontWeight.w600)),const SizedBox(height:30),TextField(controller:emailController,keyboardType:TextInputType.emailAddress,decoration:InputDecoration(labelText:'Email',prefixIcon:const Icon(Icons.email_outlined),filled:true,fillColor:const Color(0xffF5F9FF),border:OutlineInputBorder(borderRadius:BorderRadius.circular(16),borderSide:BorderSide.none))),const SizedBox(height:16),TextField(controller:passwordController,obscureText:true,onSubmitted:(_)=>_loading?null:_login(),decoration:InputDecoration(labelText:'Password',prefixIcon:const Icon(Icons.lock_outline),filled:true,fillColor:const Color(0xffF5F9FF),border:OutlineInputBorder(borderRadius:BorderRadius.circular(16),borderSide:BorderSide.none))),const SizedBox(height:24),SizedBox(width:double.infinity,height:54,child:ElevatedButton.icon(onPressed:_loading?null:_login,icon:_loading?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.login_rounded),label:Text(_loading?'Checking...':'Login',style:const TextStyle(fontSize:16,fontWeight:FontWeight.w700)),style:ElevatedButton.styleFrom(backgroundColor:const Color(0xff1769E0),foregroundColor:Colors.white,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16))))),const SizedBox(height:18),const Text('Secure Admin Access',style:TextStyle(color:Color(0xff64748B),fontSize:12))]))))))]));
}
class _WaterPainter extends CustomPainter { final double progress; _WaterPainter(this.progress); @override void paint(Canvas canvas,Size size){final rect=Offset.zero&size;canvas.drawRect(rect,Paint()..shader=const LinearGradient(begin:Alignment.topLeft,end:Alignment.bottomRight,colors:[Color(0xffEAF7FF),Color(0xffF7FBFF),Color(0xffDDF1FF)]).createShader(rect));final p=Paint()..color=const Color(0xff79CFFF).withOpacity(.14);final p2=Paint()..color=const Color(0xff2D8CFF).withOpacity(.07);_wave(canvas,size,p,.35,progress*math.pi*2);_wave(canvas,size,p2,.50,-progress*math.pi*2);}void _wave(Canvas c,Size s,Paint p,double h,double phase){final path=Path()..moveTo(0,s.height*h);for(double x=0;x<=s.width;x+=12){path.lineTo(x,s.height*h+math.sin((x/s.width)*math.pi*3+phase)*24);}path.lineTo(s.width,s.height);path.lineTo(0,s.height);path.close();c.drawPath(path,p);}@override bool shouldRepaint(covariant _WaterPainter old)=>old.progress!=progress;}
